In [2]:
import pandas as pd  
import numpy as np

In [3]:
df = pd.read_csv(r'F:\LLMS\May month task\Product_QA_Agent\data\laptop_price.csv',encoding='latin1')

In [4]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [5]:
df['Product'].nunique()

618

In [6]:
df.drop(columns=['laptop_ID'], inplace=True)

In [7]:
df.shape

(1303, 12)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   str
 1   Product           1303 non-null   str
 2   TypeName          1303 non-null   str
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   str
 5   Cpu               1303 non-null   str
 6   Ram               1303 non-null   str
 7   Memory            1303 non-null   str
 8   Gpu               1303 non-null   str
 9   OpSys             1303 non-null   str
 10  Weight            1303 non-null   str
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), str(10)
memory usage: 280.9 KB

In [9]:
df.isnull().sum()

Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(28)

In [11]:
df[df['Price_euros'] == df['Price_euros'].max()].head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
196,Razer,Blade Pro,Gaming,17.3,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7820HK 2.9GHz,32GB,1TB SSD,Nvidia GeForce GTX 1080,Windows 10,3.49kg,6099.0

In [12]:
df[df['Price_euros'] == df['Price_euros'].min()].head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1215,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,174.0

In [13]:
df['Price_euros'].mean()

np.float64(1123.6869915579432)

In [15]:
df['Price_euros'].loc[df['Company'] == "HP" ].mean()

np.float64(1067.7748540145985)

In [16]:
df['Price_euros'].loc[df['Company'] == "Apple" ].mean()

np.float64(1564.1985714285713)